// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.liujiang.nettylearn.protobuf.proto;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required int32 password = 2;</code>
     */
    boolean hasPassword();
    /**
     * <code>required int32 password = 2;</code>
     */
    int getPassword();

    /**
     * <code>optional int64 phone = 3;</code>
     */
    boolean hasPhone();
    /**
     * <code>optional int64 phone = 3;</code>
     */
    long getPhone();

    /**
     * <code>repeated string hobby = 4;</code>
     */
    com.google.protobuf.ProtocolStringList
        getHobbyList();
    /**
     * <code>repeated string hobby = 4;</code>
     */
    int getHobbyCount();
    /**
     * <code>repeated string hobby = 4;</code>
     */
    java.lang.String getHobby(int index);
    /**
     * <code>repeated string hobby = 4;</code>
     */
    com.google.protobuf.ByteString
        getHobbyBytes(int index);

    /**
     * <code>optional string sex = 5;</code>
     */
    boolean hasSex();
    /**
     * <code>optional string sex = 5;</code>
     */
    java.lang.String getSex();
    /**
     * <code>optional string sex = 5;</code>
     */
    com.google.protobuf.ByteString
        getSexBytes();

    /**
     * <code>optional .User.UserStatus user = 6 [default = OFF_LINE];</code>
     */
    boolean hasUser();
    /**
     * <code>optional .User.UserStatus user = 6 [default = OFF_LINE];</code>
     */
    com.liujiang.nettylearn.protobuf.proto.UserProto.User.UserStatus getUser();

    /**
     * <code>optional .User.Address address = 7;</code>
     */
    boolean hasAddress();
    /**
     * <code>optional .User.Address address = 7;</code>
     */
    com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address getAddress();
    /**
     * <code>optional .User.Address address = 7;</code>
     */
    com.liujiang.nettylearn.protobuf.proto.UserProto.User.AddressOrBuilder getAddressOrBuilder();
  }
  /**
   * Protobuf type {@code User}
   */
  public static final class User extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:User)
      UserOrBuilder {
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private User(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final User defaultInstance;
    public static User getDefaultInstance() {
      return defaultInstance;
    }

    public User getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              password_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              phone_ = input.readInt64();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                hobby_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              hobby_.add(bs);
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              sex_ = bs;
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
              com.liujiang.nettylearn.protobuf.proto.UserProto.User.UserStatus value = com.liujiang.nettylearn.protobuf.proto.UserProto.User.UserStatus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000010;
                user_ = value;
              }
              break;
            }
            case 58: {
              com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) == 0x00000020)) {
                subBuilder = address_.toBuilder();
              }
              address_ = input.readMessage(com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(address_);
                address_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          hobby_ = hobby_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.liujiang.nettylearn.protobuf.proto.UserProto.internal_static_User_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.liujiang.nettylearn.protobuf.proto.UserProto.internal_static_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.liujiang.nettylearn.protobuf.proto.UserProto.User.class, com.liujiang.nettylearn.protobuf.proto.UserProto.User.Builder.class);
    }

    public static com.google.protobuf.Parser<User> PARSER =
        new com.google.protobuf.AbstractParser<User>() {
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code User.UserStatus}
     */
    public enum UserStatus
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>OFF_LINE = 0;</code>
       *
       * <pre>
       *离线用户
       * </pre>
       */
      OFF_LINE(0, 0),
      /**
       * <code>ON_LINE = 1;</code>
       *
       * <pre>
       *在线用户
       * </pre>
       */
      ON_LINE(1, 1),
      ;

      /**
       * <code>OFF_LINE = 0;</code>
       *
       * <pre>
       *离线用户
       * </pre>
       */
      public static final int OFF_LINE_VALUE = 0;
      /**
       * <code>ON_LINE = 1;</code>
       *
       * <pre>
       *在线用户
       * </pre>
       */
      public static final int ON_LINE_VALUE = 1;


      public final int getNumber() { return value; }

      public static UserStatus valueOf(int value) {
        switch (value) {
          case 0: return OFF_LINE;
          case 1: return ON_LINE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<UserStatus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<UserStatus>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<UserStatus>() {
              public UserStatus findValueByNumber(int number) {
                return UserStatus.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.liujiang.nettylearn.protobuf.proto.UserProto.User.getDescriptor().getEnumTypes().get(0);
      }

      private static final UserStatus[] VALUES = values();

      public static UserStatus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private UserStatus(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:User.UserStatus)
    }

    public interface AddressOrBuilder extends
        // @@protoc_insertion_point(interface_extends:User.Address)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string province = 1;</code>
       */
      boolean hasProvince();
      /**
       * <code>optional string province = 1;</code>
       */
      java.lang.String getProvince();
      /**
       * <code>optional string province = 1;</code>
       */
      com.google.protobuf.ByteString
          getProvinceBytes();

      /**
       * <code>required int32 postcode = 2;</code>
       */
      boolean hasPostcode();
      /**
       * <code>required int32 postcode = 2;</code>
       */
      int getPostcode();
    }
    /**
     * Protobuf type {@code User.Address}
     */
    public static final class Address extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:User.Address)
        AddressOrBuilder {
      // Use Address.newBuilder() to construct.
      private Address(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Address(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Address defaultInstance;
      public static Address getDefaultInstance() {
        return defaultInstance;
      }

      public Address getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Address(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                province_ = bs;
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                postcode_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.liujiang.nettylearn.protobuf.proto.UserProto.internal_static_User_Address_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.liujiang.nettylearn.protobuf.proto.UserProto.internal_static_User_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address.class, com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address.Builder.class);
      }

      public static com.google.protobuf.Parser<Address> PARSER =
          new com.google.protobuf.AbstractParser<Address>() {
        public Address parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Address(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Address> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int PROVINCE_FIELD_NUMBER = 1;
      private java.lang.Object province_;
      /**
       * <code>optional string province = 1;</code>
       */
      public boolean hasProvince() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string province = 1;</code>
       */
      public java.lang.String getProvince() {
        java.lang.Object ref = province_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            province_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string province = 1;</code>
       */
      public com.google.protobuf.ByteString
          getProvinceBytes() {
        java.lang.Object ref = province_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          province_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int POSTCODE_FIELD_NUMBER = 2;
      private int postcode_;
      /**
       * <code>required int32 postcode = 2;</code>
       */
      public boolean hasPostcode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 postcode = 2;</code>
       */
      public int getPostcode() {
        return postcode_;
      }

      private void initFields() {
        province_ = "";
        postcode_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasPostcode()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getProvinceBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, postcode_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getProvinceBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, postcode_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code User.Address}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:User.Address)
          com.liujiang.nettylearn.protobuf.proto.UserProto.User.AddressOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.liujiang.nettylearn.protobuf.proto.UserProto.internal_static_User_Address_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.liujiang.nettylearn.protobuf.proto.UserProto.internal_static_User_Address_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address.class, com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address.Builder.class);
        }

        // Construct using com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          province_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          postcode_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.liujiang.nettylearn.protobuf.proto.UserProto.internal_static_User_Address_descriptor;
        }

        public com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address getDefaultInstanceForType() {
          return com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address.getDefaultInstance();
        }

        public com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address build() {
          com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address buildPartial() {
          com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address result = new com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.province_ = province_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.postcode_ = postcode_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address) {
            return mergeFrom((com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address other) {
          if (other == com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address.getDefaultInstance()) return this;
          if (other.hasProvince()) {
            bitField0_ |= 0x00000001;
            province_ = other.province_;
            onChanged();
          }
          if (other.hasPostcode()) {
            setPostcode(other.getPostcode());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasPostcode()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object province_ = "";
        /**
         * <code>optional string province = 1;</code>
         */
        public boolean hasProvince() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string province = 1;</code>
         */
        public java.lang.String getProvince() {
          java.lang.Object ref = province_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              province_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string province = 1;</code>
         */
        public com.google.protobuf.ByteString
            getProvinceBytes() {
          java.lang.Object ref = province_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            province_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string province = 1;</code>
         */
        public Builder setProvince(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          province_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string province = 1;</code>
         */
        public Builder clearProvince() {
          bitField0_ = (bitField0_ & ~0x00000001);
          province_ = getDefaultInstance().getProvince();
          onChanged();
          return this;
        }
        /**
         * <code>optional string province = 1;</code>
         */
        public Builder setProvinceBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          province_ = value;
          onChanged();
          return this;
        }

        private int postcode_ ;
        /**
         * <code>required int32 postcode = 2;</code>
         */
        public boolean hasPostcode() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int32 postcode = 2;</code>
         */
        public int getPostcode() {
          return postcode_;
        }
        /**
         * <code>required int32 postcode = 2;</code>
         */
        public Builder setPostcode(int value) {
          bitField0_ |= 0x00000002;
          postcode_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 postcode = 2;</code>
         */
        public Builder clearPostcode() {
          bitField0_ = (bitField0_ & ~0x00000002);
          postcode_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:User.Address)
      }

      static {
        defaultInstance = new Address(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:User.Address)
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private int password_;
    /**
     * <code>required int32 password = 2;</code>
     */
    public boolean hasPassword() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 password = 2;</code>
     */
    public int getPassword() {
      return password_;
    }

    public static final int PHONE_FIELD_NUMBER = 3;
    private long phone_;
    /**
     * <code>optional int64 phone = 3;</code>
     */
    public boolean hasPhone() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 phone = 3;</code>
     */
    public long getPhone() {
      return phone_;
    }

    public static final int HOBBY_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList hobby_;
    /**
     * <code>repeated string hobby = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getHobbyList() {
      return hobby_;
    }
    /**
     * <code>repeated string hobby = 4;</code>
     */
    public int getHobbyCount() {
      return hobby_.size();
    }
    /**
     * <code>repeated string hobby = 4;</code>
     */
    public java.lang.String getHobby(int index) {
      return hobby_.get(index);
    }
    /**
     * <code>repeated string hobby = 4;</code>
     */
    public com.google.protobuf.ByteString
        getHobbyBytes(int index) {
      return hobby_.getByteString(index);
    }

    public static final int SEX_FIELD_NUMBER = 5;
    private java.lang.Object sex_;
    /**
     * <code>optional string sex = 5;</code>
     */
    public boolean hasSex() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string sex = 5;</code>
     */
    public java.lang.String getSex() {
      java.lang.Object ref = sex_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sex_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sex = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSexBytes() {
      java.lang.Object ref = sex_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sex_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_FIELD_NUMBER = 6;
    private com.liujiang.nettylearn.protobuf.proto.UserProto.User.UserStatus user_;
    /**
     * <code>optional .User.UserStatus user = 6 [default = OFF_LINE];</code>
     */
    public boolean hasUser() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .User.UserStatus user = 6 [default = OFF_LINE];</code>
     */
    public com.liujiang.nettylearn.protobuf.proto.UserProto.User.UserStatus getUser() {
      return user_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 7;
    private com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address address_;
    /**
     * <code>optional .User.Address address = 7;</code>
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .User.Address address = 7;</code>
     */
    public com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address getAddress() {
      return address_;
    }
    /**
     * <code>optional .User.Address address = 7;</code>
     */
    public com.liujiang.nettylearn.protobuf.proto.UserProto.User.AddressOrBuilder getAddressOrBuilder() {
      return address_;
    }

    private void initFields() {
      name_ = "";
      password_ = 0;
      phone_ = 0L;
      hobby_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      sex_ = "";
      user_ = com.liujiang.nettylearn.protobuf.proto.UserProto.User.UserStatus.OFF_LINE;
      address_ = com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPassword()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasAddress()) {
        if (!getAddress().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, password_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, phone_);
      }
      for (int i = 0; i < hobby_.size(); i++) {
        output.writeBytes(4, hobby_.getByteString(i));
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getSexBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeEnum(6, user_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(7, address_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, password_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, phone_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < hobby_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(hobby_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getHobbyList().size();
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getSexBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, user_.getNumber());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, address_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.liujiang.nettylearn.protobuf.proto.UserProto.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.liujiang.nettylearn.protobuf.proto.UserProto.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.liujiang.nettylearn.protobuf.proto.UserProto.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.liujiang.nettylearn.protobuf.proto.UserProto.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.liujiang.nettylearn.protobuf.proto.UserProto.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.liujiang.nettylearn.protobuf.proto.UserProto.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.liujiang.nettylearn.protobuf.proto.UserProto.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.liujiang.nettylearn.protobuf.proto.UserProto.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.liujiang.nettylearn.protobuf.proto.UserProto.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.liujiang.nettylearn.protobuf.proto.UserProto.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.liujiang.nettylearn.protobuf.proto.UserProto.User prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:User)
        com.liujiang.nettylearn.protobuf.proto.UserProto.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.liujiang.nettylearn.protobuf.proto.UserProto.internal_static_User_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.liujiang.nettylearn.protobuf.proto.UserProto.internal_static_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.liujiang.nettylearn.protobuf.proto.UserProto.User.class, com.liujiang.nettylearn.protobuf.proto.UserProto.User.Builder.class);
      }

      // Construct using com.liujiang.nettylearn.protobuf.proto.UserProto.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAddressFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        password_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        phone_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        hobby_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        sex_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        user_ = com.liujiang.nettylearn.protobuf.proto.UserProto.User.UserStatus.OFF_LINE;
        bitField0_ = (bitField0_ & ~0x00000020);
        if (addressBuilder_ == null) {
          address_ = com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address.getDefaultInstance();
        } else {
          addressBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.liujiang.nettylearn.protobuf.proto.UserProto.internal_static_User_descriptor;
      }

      public com.liujiang.nettylearn.protobuf.proto.UserProto.User getDefaultInstanceForType() {
        return com.liujiang.nettylearn.protobuf.proto.UserProto.User.getDefaultInstance();
      }

      public com.liujiang.nettylearn.protobuf.proto.UserProto.User build() {
        com.liujiang.nettylearn.protobuf.proto.UserProto.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.liujiang.nettylearn.protobuf.proto.UserProto.User buildPartial() {
        com.liujiang.nettylearn.protobuf.proto.UserProto.User result = new com.liujiang.nettylearn.protobuf.proto.UserProto.User(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.password_ = password_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.phone_ = phone_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          hobby_ = hobby_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.hobby_ = hobby_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sex_ = sex_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.user_ = user_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        if (addressBuilder_ == null) {
          result.address_ = address_;
        } else {
          result.address_ = addressBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.liujiang.nettylearn.protobuf.proto.UserProto.User) {
          return mergeFrom((com.liujiang.nettylearn.protobuf.proto.UserProto.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.liujiang.nettylearn.protobuf.proto.UserProto.User other) {
        if (other == com.liujiang.nettylearn.protobuf.proto.UserProto.User.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasPassword()) {
          setPassword(other.getPassword());
        }
        if (other.hasPhone()) {
          setPhone(other.getPhone());
        }
        if (!other.hobby_.isEmpty()) {
          if (hobby_.isEmpty()) {
            hobby_ = other.hobby_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureHobbyIsMutable();
            hobby_.addAll(other.hobby_);
          }
          onChanged();
        }
        if (other.hasSex()) {
          bitField0_ |= 0x00000010;
          sex_ = other.sex_;
          onChanged();
        }
        if (other.hasUser()) {
          setUser(other.getUser());
        }
        if (other.hasAddress()) {
          mergeAddress(other.getAddress());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasPassword()) {
          
          return false;
        }
        if (hasAddress()) {
          if (!getAddress().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.liujiang.nettylearn.protobuf.proto.UserProto.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.liujiang.nettylearn.protobuf.proto.UserProto.User) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private int password_ ;
      /**
       * <code>required int32 password = 2;</code>
       */
      public boolean hasPassword() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 password = 2;</code>
       */
      public int getPassword() {
        return password_;
      }
      /**
       * <code>required int32 password = 2;</code>
       */
      public Builder setPassword(int value) {
        bitField0_ |= 0x00000002;
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 password = 2;</code>
       */
      public Builder clearPassword() {
        bitField0_ = (bitField0_ & ~0x00000002);
        password_ = 0;
        onChanged();
        return this;
      }

      private long phone_ ;
      /**
       * <code>optional int64 phone = 3;</code>
       */
      public boolean hasPhone() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 phone = 3;</code>
       */
      public long getPhone() {
        return phone_;
      }
      /**
       * <code>optional int64 phone = 3;</code>
       */
      public Builder setPhone(long value) {
        bitField0_ |= 0x00000004;
        phone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 phone = 3;</code>
       */
      public Builder clearPhone() {
        bitField0_ = (bitField0_ & ~0x00000004);
        phone_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList hobby_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureHobbyIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          hobby_ = new com.google.protobuf.LazyStringArrayList(hobby_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string hobby = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getHobbyList() {
        return hobby_.getUnmodifiableView();
      }
      /**
       * <code>repeated string hobby = 4;</code>
       */
      public int getHobbyCount() {
        return hobby_.size();
      }
      /**
       * <code>repeated string hobby = 4;</code>
       */
      public java.lang.String getHobby(int index) {
        return hobby_.get(index);
      }
      /**
       * <code>repeated string hobby = 4;</code>
       */
      public com.google.protobuf.ByteString
          getHobbyBytes(int index) {
        return hobby_.getByteString(index);
      }
      /**
       * <code>repeated string hobby = 4;</code>
       */
      public Builder setHobby(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHobbyIsMutable();
        hobby_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hobby = 4;</code>
       */
      public Builder addHobby(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHobbyIsMutable();
        hobby_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hobby = 4;</code>
       */
      public Builder addAllHobby(
          java.lang.Iterable<java.lang.String> values) {
        ensureHobbyIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, hobby_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hobby = 4;</code>
       */
      public Builder clearHobby() {
        hobby_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string hobby = 4;</code>
       */
      public Builder addHobbyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHobbyIsMutable();
        hobby_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object sex_ = "";
      /**
       * <code>optional string sex = 5;</code>
       */
      public boolean hasSex() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string sex = 5;</code>
       */
      public java.lang.String getSex() {
        java.lang.Object ref = sex_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sex_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sex = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSexBytes() {
        java.lang.Object ref = sex_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sex_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sex = 5;</code>
       */
      public Builder setSex(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sex = 5;</code>
       */
      public Builder clearSex() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sex_ = getDefaultInstance().getSex();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sex = 5;</code>
       */
      public Builder setSexBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        sex_ = value;
        onChanged();
        return this;
      }

      private com.liujiang.nettylearn.protobuf.proto.UserProto.User.UserStatus user_ = com.liujiang.nettylearn.protobuf.proto.UserProto.User.UserStatus.OFF_LINE;
      /**
       * <code>optional .User.UserStatus user = 6 [default = OFF_LINE];</code>
       */
      public boolean hasUser() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .User.UserStatus user = 6 [default = OFF_LINE];</code>
       */
      public com.liujiang.nettylearn.protobuf.proto.UserProto.User.UserStatus getUser() {
        return user_;
      }
      /**
       * <code>optional .User.UserStatus user = 6 [default = OFF_LINE];</code>
       */
      public Builder setUser(com.liujiang.nettylearn.protobuf.proto.UserProto.User.UserStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        user_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .User.UserStatus user = 6 [default = OFF_LINE];</code>
       */
      public Builder clearUser() {
        bitField0_ = (bitField0_ & ~0x00000020);
        user_ = com.liujiang.nettylearn.protobuf.proto.UserProto.User.UserStatus.OFF_LINE;
        onChanged();
        return this;
      }

      private com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address address_ = com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address, com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address.Builder, com.liujiang.nettylearn.protobuf.proto.UserProto.User.AddressOrBuilder> addressBuilder_;
      /**
       * <code>optional .User.Address address = 7;</code>
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .User.Address address = 7;</code>
       */
      public com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address getAddress() {
        if (addressBuilder_ == null) {
          return address_;
        } else {
          return addressBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .User.Address address = 7;</code>
       */
      public Builder setAddress(com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          address_ = value;
          onChanged();
        } else {
          addressBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .User.Address address = 7;</code>
       */
      public Builder setAddress(
          com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address.Builder builderForValue) {
        if (addressBuilder_ == null) {
          address_ = builderForValue.build();
          onChanged();
        } else {
          addressBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .User.Address address = 7;</code>
       */
      public Builder mergeAddress(com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address value) {
        if (addressBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              address_ != com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address.getDefaultInstance()) {
            address_ =
              com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address.newBuilder(address_).mergeFrom(value).buildPartial();
          } else {
            address_ = value;
          }
          onChanged();
        } else {
          addressBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .User.Address address = 7;</code>
       */
      public Builder clearAddress() {
        if (addressBuilder_ == null) {
          address_ = com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address.getDefaultInstance();
          onChanged();
        } else {
          addressBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      /**
       * <code>optional .User.Address address = 7;</code>
       */
      public com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address.Builder getAddressBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getAddressFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .User.Address address = 7;</code>
       */
      public com.liujiang.nettylearn.protobuf.proto.UserProto.User.AddressOrBuilder getAddressOrBuilder() {
        if (addressBuilder_ != null) {
          return addressBuilder_.getMessageOrBuilder();
        } else {
          return address_;
        }
      }
      /**
       * <code>optional .User.Address address = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address, com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address.Builder, com.liujiang.nettylearn.protobuf.proto.UserProto.User.AddressOrBuilder> 
          getAddressFieldBuilder() {
        if (addressBuilder_ == null) {
          addressBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address, com.liujiang.nettylearn.protobuf.proto.UserProto.User.Address.Builder, com.liujiang.nettylearn.protobuf.proto.UserProto.User.AddressOrBuilder>(
                  getAddress(),
                  getParentForChildren(),
                  isClean());
          address_ = null;
        }
        return addressBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:User)
    }

    static {
      defaultInstance = new User(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:User)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_Address_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_User_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nUser.proto\"\363\001\n\004User\022\014\n\004name\030\001 \002(\t\022\020\n\010p" +
      "assword\030\002 \002(\005\022\r\n\005phone\030\003 \001(\003\022\r\n\005hobby\030\004 " +
      "\003(\t\022\013\n\003sex\030\005 \001(\t\022(\n\004user\030\006 \001(\0162\020.User.Us" +
      "erStatus:\010OFF_LINE\022\036\n\007address\030\007 \001(\0132\r.Us" +
      "er.Address\032-\n\007Address\022\020\n\010province\030\001 \001(\t\022" +
      "\020\n\010postcode\030\002 \002(\005\"\'\n\nUserStatus\022\014\n\010OFF_L" +
      "INE\020\000\022\013\n\007ON_LINE\020\001B3\n&com.liujiang.netty" +
      "learn.protobuf.protoB\tUserProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "Name", "Password", "Phone", "Hobby", "Sex", "User", "Address", });
    internal_static_User_Address_descriptor =
      internal_static_User_descriptor.getNestedTypes().get(0);
    internal_static_User_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_User_Address_descriptor,
        new java.lang.String[] { "Province", "Postcode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
